export const ERROR_CODES = {
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_EXPIRED: 'REFRESH_EXPIRED',
  REFRESH_INVALID: 'REFRESH_INVALID',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOTE_NOT_FOUND: 'NOTE_NOT_FOUND',
  TAG_NOT_FOUND: 'TAG_NOT_FOUND',
  TAG_NAME_TAKEN: 'TAG_NAME_TAKEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
